### PR TITLE
Try to fix the build by using a newer scalariform version

### PR DESCRIPTION
**Pull request by fthomas**
see #6

### CODE REVIEW

**Comment by fthomas** [comment]
I'm running out of ideas...
I suggest reverting to sbt 0.13.8 until scalastyle uses a newer scalariform version (https://github.com/scalastyle/scalastyle/issues/156)

**Comment by milessabin** [comment]
Should we just drop scalastyle until it and/or SBT are unbroken?

**Comment by non** [comment]
Yeah, let's do that.

**Comment by non** [comment]
Scalastyle is nice but in the short term I'd rather have SBT 0.13.9 I think.

**Comment by fthomas** [comment]
superseded by #14

**Pull request closed without merging**
