### PR TITLE
Bumped SBT to 0.13.9.

### PR DESCRIPTION
**Pull request by milessabin**

### CODE REVIEW

**Comment by non** [comment]
Apparently SBT 0.13.9 is cursed??

**Comment by milessabin** [comment]
I have no idea what's going on there ... 0.13.9 is working for shapeless. Could it be 2.11.6 vs. 7?

**Comment by fthomas** [comment]
It seems like you're hitting https://github.com/sbt/sbt/issues/2089. Try to use a newer scalariform version in the project build, e.g. add `libraryDependencies += "org.scalariform" %% "scalariform" % "0.1.7"` to `project/plugins.sbt`. That did it for me in refined.

**Comment by non** [comment]
Tried this locally and it was OK, so I'm going to merge and hope for the best. :+1:

**Pull request merged**
