### PR TITLE
Fix #7: Add Scala.js support

### LINKED ISSUE #7: Add Scala.js support

### LINKED ISSUE #8: Add 2.10 to travis build

### PR DESCRIPTION
**Pull request by ghost**
also Fix #8

### CODE REVIEW

**Comment by non** [comment]
Thanks! Looks like there are some compilation errors.

**Comment by ghost** [comment]
@non Until the corresponding PR in cats is released, this will not compile. ie https://github.com/non/cats/pull/495 

And even then, note that the dependency is on a Cats snapshot.

**Comment by non** [comment]
Unfortunately I failed to merge the future support in Cats before releasing 0.2.0, so this will need to wait until we have a working snapshot there.

**Comment by non** [comment]
One other consideration: given that we are likely going to be moving the `Await` / `j.u.c` support into `cats.jvm`, would you rather move this stuff into `cats.js`? I'm fine with leaving it in Alleycats, but it seems like it might make life a lot easier for us to put it there instead.

**Comment by ghost** [comment]
@non Given that the cats layout is going to change, both https://github.com/non/cats/pull/495 and this PR need a major refactor regardless. 

But I also agree that it's better to move to cats, at least for the short/middle term and pre cats 1.0. But it was good to try out this route, just to see the benefits/drawbacks.

So I will close this PR.

**Pull request closed without merging**
